# Generated by fork/release/render_homebrew_formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/ore-cli/ore"
  version "1.152.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.152.1/codex-package-aarch64-apple-darwin.tar.gz"
      sha256 "854db24eb9e1dedfe1cc0513f28c6b02b8fabb096f5889db433b964426474db9"
    end
    on_intel do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.152.1/codex-package-x86_64-apple-darwin.tar.gz"
      sha256 "c699887dd17c08a007ea082e86cef290b89c08743b4dd30492cb91c510852c95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.152.1/codex-package-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d29a06d19c4bd9f19cac0299f4ec1eeec94b73a29aab400f51bf0919b76de22a"
    end
    on_intel do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.152.1/codex-package-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c3402101cf856eb18e625bd248d833ea902b384652a6a67b086a9c1e634ea488"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ore --version")
  end
end
