# Generated by fork/release/render_homebrew_formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/ore-cli/ore"
  version "1.153.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.153.4/codex-package-aarch64-apple-darwin.tar.gz"
      sha256 "5c55e42004b5874c1bba39cf4c38f749989766dcaa40c6456266ac147547f104"
    end
    on_intel do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.153.4/codex-package-x86_64-apple-darwin.tar.gz"
      sha256 "bcabc458d122e9ddbca1ce15a96e058623bc61203560c9c38dd2470eceac1722"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.153.4/codex-package-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c2763aa91fc6d1b14ac100e82b6f3f2edd216b69317c378267f648d42d7a30e1"
    end
    on_intel do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.153.4/codex-package-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8a6ebf2c3158e09342a78c04d6ffa4e156505a24ba77e841751babce138a43ba"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ore --version")
  end
end
