# Generated by fork/release/render_homebrew_formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/ore-cli/ore"
  version "1.149.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.149.0/codex-package-aarch64-apple-darwin.tar.gz"
      sha256 "bdf1a9473a85e9c12bcd8393432e7a74df9134573dcc1df5f54dd4a915c2a207"
    end
    on_intel do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.149.0/codex-package-x86_64-apple-darwin.tar.gz"
      sha256 "d861206bbed73a9c422aa3f269b40aa6f4b165ac66210e667a857c3209734895"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.149.0/codex-package-aarch64-unknown-linux-musl.tar.gz"
      sha256 "1f7eb18cd223f7d2903213e73c523b713854d9bc4fbb48d924dbd0d5074e868e"
    end
    on_intel do
      url "https://github.com/ore-cli/ore/releases/download/ore-v1.149.0/codex-package-x86_64-unknown-linux-musl.tar.gz"
      sha256 "29962d9413c2a0bcb5fd09db8bf6c8d3f2184d57af74f242987d5385aa03badb"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ore --version")
  end
end
